"""Add table admins

Revision ID: 06591bc3549e
Revises: 42d86650ceb0
Create Date: 2024-12-25 10:50:09.598546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06591bc3549e'
down_revision: Union[str, None] = '42d86650ceb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admins',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('mail_address', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('role IN (1, 2, 3)', name='check_role_valid'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('mail_address'),
    )
    op.drop_index('ix_items_id', table_name='items')
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    op.drop_table('admins')
    # ### end Alembic commands ###
